name: trackml
channels:
  - conda-forge
  - defaults
dependencies:
  - hdbscan=0.8.13
  - llvm-meta=6.0.0
  - openmp=6.0.0
  - xgboost=0.71
  - appnope=0.1.0
  - astroid=1.6.3
  - backcall=0.1.0
  - bleach=2.1.3
  - ca-certificates=2018.03.07
  - certifi=2018.4.16
  - cycler=0.10.0
  - cython=0.28.2
  - dbus=1.13.2
  - decorator=4.3.0
  - entrypoints=0.2.3
  - expat=2.2.5
  - fontconfig=2.12.6
  - freetype=2.8
  - gettext=0.19.8.1
  - glib=2.56.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.7.1
  - hdf5=1.10.1
  - html5lib=1.0.1
  - icu=58.2
  - intel-openmp=2018.0.0
  - ipykernel=4.8.2
  - ipython=6.4.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.2.1
  - isort=4.3.4
  - jedi=0.12.0
  - jinja2=2.10
  - jpeg=9b
  - jsonschema=2.6.0
  - jupyter=1.0.0
  - jupyter_client=5.2.3
  - jupyter_console=5.2.0
  - jupyter_core=4.4.0
  - keras=2.1.5
  - kiwisolver=1.0.1
  - lazy-object-proxy=1.3.1
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libgfortran-ng=3.0.1
  - libiconv=1.15
  - libpng=1.6.34
  - libprotobuf=3.5.2
  - libsodium=1.0.16
  - libxml2=2.9.8
  - markupsafe=1.0
  - matplotlib=2.2.2
  - mccabe=0.6.1
  - mistune=0.8.3
  - mkl=2018.0.2
  - mkl_fft=1.0.1
  - mkl_random=1.0.1
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - ncurses=6.0
  - notebook=5.4.1
  - numpy=1.12.1
  - openssl=1.0.2o
  - pandas=0.22.0
  - pandoc=1.19.2.1
  - pandocfilters=1.4.2
  - parso=0.2.0
  - patsy=0.5.0
  - pcre=8.42
  - pexpect=4.5.0
  - pickleshare=0.7.4
  - pip=10.0.1
  - prompt_toolkit=1.0.15
  - protobuf=3.5.2
  - ptyprocess=0.5.2
  - pygments=2.2.0
  - pylint=1.8.4
  - pyparsing=2.2.0
  - pyqt=5.9.2
  - python=3.6.5
  - python-dateutil=2.7.2
  - pytz=2018.4
  - pyyaml=3.12
  - pyzmq=17.0.0
  - qt=5.9.5
  - qtconsole=4.3.1
  - readline=7.0
  - scikit-learn=0.19.1
  - scipy=1.0.1
  - seaborn=0.8.1
  - send2trash=1.5.0
  - setuptools=39.1.0
  - simplegeneric=0.8.1
  - sip=4.19.8
  - six=1.11.0
  - sqlite=3.23.1
  - statsmodels=0.9.0
  - tensorflow=1.1.0
  - terminado=0.8.1
  - testpath=0.3.1
  - tk=8.6.7
  - tornado=5.0.2
  - tqdm=4.23.0
  - traitlets=4.3.2
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - werkzeug=0.14.1
  - wheel=0.31.0
  - widgetsnbextension=3.2.1
  - wrapt=1.10.11
  - xz=5.2.3
  - yaml=0.1.7
  - zeromq=4.2.5
  - zlib=1.2.11
  - pip:
    - trackml==2

